trigger:
  - master

strategy:
  matrix:
    ubuntu:
      CC: gcc
      CXX: g++
      IMAGE_NAME: 'ubuntu-16.04'
    mac:
      CC: clang
      CXX: clang++
      IMAGE_NAME: 'macos-10.15'

pool:
  vmImage: $(IMAGE_NAME)

steps:
  - checkout: self
    submodules: false

  - script: |
      git clone --branch 3.3.7 https://github.com/eigenteam/eigen-git-mirror.git
      pushd eigen-git-mirror
      mkdir build && cd build
      cmake .. && sudo make install
      popd
    displayName: 'Install Eigen'

  - script: |
      pushd EKF
      mkdir build && cd build
      cmake .. && make
      popd
    displayName: 'Build EKF project'

  - script: |
      pushd UKF
      mkdir build && cd build
      cmake .. && make
      popd
    displayName: 'Build UKF project'

  - script: |
      if [[ $(CC) == 'gcc' ]]; then
        sudo apt install libpcl-dev
      fi
      # TODO: FIX me
      # brew install pcl
    displayName: 'Install PCL'

  - script: |
      if [[ $(CC) == 'gcc' ]]; then
        pushd SFND_Lidar_Obstacle_Detection
        mkdir build && cd build
        cmake .. -DBUILD_TEST=ON && make && make test
        cmake .. -DBUILD_TEST=ON -DUSE_PCL_SEG=ON -DUSE_PCL_CLUSTER=ON && make && make test
        popd
      fi
    displayName: 'Build LIDAR obstacle detection project'
